import { CANCEL } from 'redux-saga';
import Dashboard from '../screens/LocalTripDashboard';

export const APP_ICONS = {
    GOD: require('../../assets/icons/bootSplash.png'),
    BACK: require('../../assets/icons/backArrow.png'),
    HAMBURGER: require('../../assets/icons/hamburger.png'),
    NOTIFICATION_BELL: require('../../assets/icons/notificationBell.png'),
    CAR: require('../../assets/icons/car.png'),
    CAR_SEDAN: require('../../assets/icons/car_sedan.png'),
    HISTORY_CLOCK: require('../../assets/icons/historyClock.png'),
    CURRENCY: require('../../assets/icons/currency.png'),
    HEADPHONE: require('../../assets/icons/headphone.png'),
    INFO: require('../../assets/icons/info.png'),
    LOGOUT: require('../../assets/icons/logout.png'),
    UPI: require('../../assets/icons/upi.png'),
    CIRCLE_GREEN: require('../../assets/icons/circleGreen.png'),
    CIRCLE_RED: require('../../assets/icons/circleRed.png'),
    MINI: require('../../assets/icons/miniOutline.png'),
    SEDAN: require('../../assets/icons/sedanOutline.png'),
    SUV: require('../../assets/icons/suvOutline.png'),
    DAILY: require('../../assets/icons/daily.png'),
    OUTSTATION: require('../../assets/icons/outstation.png'),
    RENTAL: require('../../assets/icons/rental.png'),
    CALENDER: require('../../assets/icons/calender.png'),
    USER: require('../../assets/icons/user.png'),
    COUPON: require('../../assets/icons/coupon.png'),
    ARROW_DOWN: require('../../assets/icons/arrowDown.png'),
    ARROW_RIGHT_LONG: require('../../assets/icons/rightArrow.png'),
    DOUBLE_END_ARROW: require('../../assets/icons/doubleEndArrow.png'),
    MENU: require('../../assets/icons/menu.png'),
    MENU_DOTS: require('../../assets/icons/menu-dots.png'),
    LOCATION: require('../../assets/icons/my location.png'),
    CUSTOMER: require('../../assets/icons/customer-support.png'),
    NOTIFICATION_BELL: require('../../assets/icons/notificationBell.png'),
    TRIPTYPE: require('../../assets/icons/trip.png'),
   DASHBOARD: require('../../assets/icons/dashboard.png'),
   CALL: require('../../assets/icons/call.png'),
   TICK: require('../../assets/icons/tick.png'),
    SOS: require('../../assets/icons/sos.png'),
    SYNC: require('../../assets/icons/sysn.png'),
    CANCEL: require('../../assets/icons/cancel.png'),
    LOGINIMAGE1: require('../../assets/icons/Loginimage.png'),
    BATTERY: require('../../assets/icons/battery.png'),
    PERMISSIONANDORID: require('../../assets/icons/permissionandroid.png'),
    PERMISSIONOVERLAY: require('../../assets/icons/permissionoverlay.png'),
    PERMISSIONLOCATION: require('../../assets/icons/PermissionLocation.png'),
}